; --- Config commune ---
[env]
platform = espressif32@6.10.0
board = adafruit_qtpy_esp32c3
framework = arduino
board_build.partitions = min_spiffs.csv   ; 🔴 OTA + grosse app

lib_deps =
    knolleary/PubSubClient @ ^2.8

monitor_speed = 115200

build_flags =
    -DARDUINO_JSON_NO_STATIC_STRINGS
    -DARDUINO_JSON_NO_FLOAT
    -Os
    -Wl,--gc-sections
    -fno-exceptions
    -ffunction-sections
    -fdata-sections
    ; ⚠️  OTA HMAC-SHA256 — doit correspondre à OTA_HMAC_KEY dans .env.prod du backend
    ; ⚠️  CHANGER cette valeur avant tout déploiement en production
    -DOTA_HMAC_KEY='"60e9552aea56b819ff7648fed534cc1a21801287c536b26832880fda7f870c04"'

build_type = release


; --- Env principal (USB) ---
[env:xamiot]
upload_protocol = esptool
upload_speed = 115200
