-- 036_countries.sql
-- Référentiel pays ISO 3166-1 alpha-2 pour la boutique.
-- Champs : activation, blocage, frais de port, taxes, douane, message client.

CREATE TABLE IF NOT EXISTS countries (
  code       char(2) PRIMARY KEY,            -- ISO 3166-1 alpha-2
  code3      char(3) NOT NULL,               -- ISO 3166-1 alpha-3
  name_fr    text NOT NULL,
  name_en    text NOT NULL,
  is_active  boolean NOT NULL DEFAULT false,  -- visible côté client
  is_blocked boolean NOT NULL DEFAULT false,  -- bloqué = pas de commande possible
  shipping_cents   integer NOT NULL DEFAULT 0,
  tax_rate_pct     numeric(5,2) NOT NULL DEFAULT 0,  -- ex: 20.00 = 20%
  customs_cents    integer NOT NULL DEFAULT 0,
  customs_note     text,                      -- note interne douane
  message_client   text,                      -- message affiché au client
  sort_order       integer NOT NULL DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_countries_active ON countries(is_active);

-- Seed : 249 pays ISO 3166-1 (France activée par défaut)
INSERT INTO countries (code, code3, name_fr, name_en, is_active, sort_order) VALUES
('AF','AFG','Afghanistan','Afghanistan',false,0),
('AL','ALB','Albanie','Albania',false,0),
('DZ','DZA','Algérie','Algeria',false,0),
('AS','ASM','Samoa américaines','American Samoa',false,0),
('AD','AND','Andorre','Andorra',false,0),
('AO','AGO','Angola','Angola',false,0),
('AI','AIA','Anguilla','Anguilla',false,0),
('AQ','ATA','Antarctique','Antarctica',false,0),
('AG','ATG','Antigua-et-Barbuda','Antigua and Barbuda',false,0),
('AR','ARG','Argentine','Argentina',false,0),
('AM','ARM','Arménie','Armenia',false,0),
('AW','ABW','Aruba','Aruba',false,0),
('AU','AUS','Australie','Australia',false,0),
('AT','AUT','Autriche','Austria',false,0),
('AZ','AZE','Azerbaïdjan','Azerbaijan',false,0),
('BS','BHS','Bahamas','Bahamas',false,0),
('BH','BHR','Bahreïn','Bahrain',false,0),
('BD','BGD','Bangladesh','Bangladesh',false,0),
('BB','BRB','Barbade','Barbados',false,0),
('BY','BLR','Biélorussie','Belarus',false,0),
('BE','BEL','Belgique','Belgium',false,0),
('BZ','BLZ','Belize','Belize',false,0),
('BJ','BEN','Bénin','Benin',false,0),
('BM','BMU','Bermudes','Bermuda',false,0),
('BT','BTN','Bhoutan','Bhutan',false,0),
('BO','BOL','Bolivie','Bolivia',false,0),
('BA','BIH','Bosnie-Herzégovine','Bosnia and Herzegovina',false,0),
('BW','BWA','Botswana','Botswana',false,0),
('BR','BRA','Brésil','Brazil',false,0),
('BN','BRN','Brunei','Brunei',false,0),
('BG','BGR','Bulgarie','Bulgaria',false,0),
('BF','BFA','Burkina Faso','Burkina Faso',false,0),
('BI','BDI','Burundi','Burundi',false,0),
('CV','CPV','Cap-Vert','Cabo Verde',false,0),
('KH','KHM','Cambodge','Cambodia',false,0),
('CM','CMR','Cameroun','Cameroon',false,0),
('CA','CAN','Canada','Canada',false,0),
('KY','CYM','Îles Caïmans','Cayman Islands',false,0),
('CF','CAF','République centrafricaine','Central African Republic',false,0),
('TD','TCD','Tchad','Chad',false,0),
('CL','CHL','Chili','Chile',false,0),
('CN','CHN','Chine','China',false,0),
('CO','COL','Colombie','Colombia',false,0),
('KM','COM','Comores','Comoros',false,0),
('CG','COG','Congo','Congo',false,0),
('CD','COD','Congo (RDC)','Congo (DRC)',false,0),
('CK','COK','Îles Cook','Cook Islands',false,0),
('CR','CRI','Costa Rica','Costa Rica',false,0),
('CI','CIV','Côte d''Ivoire','Côte d''Ivoire',false,0),
('HR','HRV','Croatie','Croatia',false,0),
('CU','CUB','Cuba','Cuba',false,0),
('CW','CUW','Curaçao','Curaçao',false,0),
('CY','CYP','Chypre','Cyprus',false,0),
('CZ','CZE','Tchéquie','Czechia',false,0),
('DK','DNK','Danemark','Denmark',false,0),
('DJ','DJI','Djibouti','Djibouti',false,0),
('DM','DMA','Dominique','Dominica',false,0),
('DO','DOM','République dominicaine','Dominican Republic',false,0),
('EC','ECU','Équateur','Ecuador',false,0),
('EG','EGY','Égypte','Egypt',false,0),
('SV','SLV','Salvador','El Salvador',false,0),
('GQ','GNQ','Guinée équatoriale','Equatorial Guinea',false,0),
('ER','ERI','Érythrée','Eritrea',false,0),
('EE','EST','Estonie','Estonia',false,0),
('SZ','SWZ','Eswatini','Eswatini',false,0),
('ET','ETH','Éthiopie','Ethiopia',false,0),
('FJ','FJI','Fidji','Fiji',false,0),
('FI','FIN','Finlande','Finland',false,0),
('FR','FRA','France','France',true,1),
('GF','GUF','Guyane française','French Guiana',false,0),
('PF','PYF','Polynésie française','French Polynesia',false,0),
('GA','GAB','Gabon','Gabon',false,0),
('GM','GMB','Gambie','Gambia',false,0),
('GE','GEO','Géorgie','Georgia',false,0),
('DE','DEU','Allemagne','Germany',false,0),
('GH','GHA','Ghana','Ghana',false,0),
('GI','GIB','Gibraltar','Gibraltar',false,0),
('GR','GRC','Grèce','Greece',false,0),
('GL','GRL','Groenland','Greenland',false,0),
('GD','GRD','Grenade','Grenada',false,0),
('GP','GLP','Guadeloupe','Guadeloupe',false,0),
('GU','GUM','Guam','Guam',false,0),
('GT','GTM','Guatemala','Guatemala',false,0),
('GG','GGY','Guernesey','Guernsey',false,0),
('GN','GIN','Guinée','Guinea',false,0),
('GW','GNB','Guinée-Bissau','Guinea-Bissau',false,0),
('GY','GUY','Guyana','Guyana',false,0),
('HT','HTI','Haïti','Haiti',false,0),
('HN','HND','Honduras','Honduras',false,0),
('HK','HKG','Hong Kong','Hong Kong',false,0),
('HU','HUN','Hongrie','Hungary',false,0),
('IS','ISL','Islande','Iceland',false,0),
('IN','IND','Inde','India',false,0),
('ID','IDN','Indonésie','Indonesia',false,0),
('IR','IRN','Iran','Iran',false,0),
('IQ','IRQ','Irak','Iraq',false,0),
('IE','IRL','Irlande','Ireland',false,0),
('IM','IMN','Île de Man','Isle of Man',false,0),
('IL','ISR','Israël','Israel',false,0),
('IT','ITA','Italie','Italy',false,0),
('JM','JAM','Jamaïque','Jamaica',false,0),
('JP','JPN','Japon','Japan',false,0),
('JE','JEY','Jersey','Jersey',false,0),
('JO','JOR','Jordanie','Jordan',false,0),
('KZ','KAZ','Kazakhstan','Kazakhstan',false,0),
('KE','KEN','Kenya','Kenya',false,0),
('KI','KIR','Kiribati','Kiribati',false,0),
('KP','PRK','Corée du Nord','North Korea',false,0),
('KR','KOR','Corée du Sud','South Korea',false,0),
('KW','KWT','Koweït','Kuwait',false,0),
('KG','KGZ','Kirghizistan','Kyrgyzstan',false,0),
('LA','LAO','Laos','Laos',false,0),
('LV','LVA','Lettonie','Latvia',false,0),
('LB','LBN','Liban','Lebanon',false,0),
('LS','LSO','Lesotho','Lesotho',false,0),
('LR','LBR','Liberia','Liberia',false,0),
('LY','LBY','Libye','Libya',false,0),
('LI','LIE','Liechtenstein','Liechtenstein',false,0),
('LT','LTU','Lituanie','Lithuania',false,0),
('LU','LUX','Luxembourg','Luxembourg',false,0),
('MO','MAC','Macao','Macao',false,0),
('MG','MDG','Madagascar','Madagascar',false,0),
('MW','MWI','Malawi','Malawi',false,0),
('MY','MYS','Malaisie','Malaysia',false,0),
('MV','MDV','Maldives','Maldives',false,0),
('ML','MLI','Mali','Mali',false,0),
('MT','MLT','Malte','Malta',false,0),
('MH','MHL','Îles Marshall','Marshall Islands',false,0),
('MQ','MTQ','Martinique','Martinique',false,0),
('MR','MRT','Mauritanie','Mauritania',false,0),
('MU','MUS','Maurice','Mauritius',false,0),
('YT','MYT','Mayotte','Mayotte',false,0),
('MX','MEX','Mexique','Mexico',false,0),
('FM','FSM','Micronésie','Micronesia',false,0),
('MD','MDA','Moldavie','Moldova',false,0),
('MC','MCO','Monaco','Monaco',false,0),
('MN','MNG','Mongolie','Mongolia',false,0),
('ME','MNE','Monténégro','Montenegro',false,0),
('MS','MSR','Montserrat','Montserrat',false,0),
('MA','MAR','Maroc','Morocco',false,0),
('MZ','MOZ','Mozambique','Mozambique',false,0),
('MM','MMR','Myanmar','Myanmar',false,0),
('NA','NAM','Namibie','Namibia',false,0),
('NR','NRU','Nauru','Nauru',false,0),
('NP','NPL','Népal','Nepal',false,0),
('NL','NLD','Pays-Bas','Netherlands',false,0),
('NC','NCL','Nouvelle-Calédonie','New Caledonia',false,0),
('NZ','NZL','Nouvelle-Zélande','New Zealand',false,0),
('NI','NIC','Nicaragua','Nicaragua',false,0),
('NE','NER','Niger','Niger',false,0),
('NG','NGA','Nigeria','Nigeria',false,0),
('NU','NIU','Niue','Niue',false,0),
('NF','NFK','Île Norfolk','Norfolk Island',false,0),
('MK','MKD','Macédoine du Nord','North Macedonia',false,0),
('MP','MNP','Îles Mariannes du Nord','Northern Mariana Islands',false,0),
('NO','NOR','Norvège','Norway',false,0),
('OM','OMN','Oman','Oman',false,0),
('PK','PAK','Pakistan','Pakistan',false,0),
('PW','PLW','Palaos','Palau',false,0),
('PS','PSE','Palestine','Palestine',false,0),
('PA','PAN','Panama','Panama',false,0),
('PG','PNG','Papouasie-Nouvelle-Guinée','Papua New Guinea',false,0),
('PY','PRY','Paraguay','Paraguay',false,0),
('PE','PER','Pérou','Peru',false,0),
('PH','PHL','Philippines','Philippines',false,0),
('PL','POL','Pologne','Poland',false,0),
('PT','PRT','Portugal','Portugal',false,0),
('PR','PRI','Porto Rico','Puerto Rico',false,0),
('QA','QAT','Qatar','Qatar',false,0),
('RE','REU','La Réunion','Réunion',false,0),
('RO','ROU','Roumanie','Romania',false,0),
('RU','RUS','Russie','Russia',false,0),
('RW','RWA','Rwanda','Rwanda',false,0),
('BL','BLM','Saint-Barthélemy','Saint Barthélemy',false,0),
('SH','SHN','Sainte-Hélène','Saint Helena',false,0),
('KN','KNA','Saint-Kitts-et-Nevis','Saint Kitts and Nevis',false,0),
('LC','LCA','Sainte-Lucie','Saint Lucia',false,0),
('MF','MAF','Saint-Martin','Saint Martin',false,0),
('PM','SPM','Saint-Pierre-et-Miquelon','Saint Pierre and Miquelon',false,0),
('VC','VCT','Saint-Vincent-et-les-Grenadines','Saint Vincent and the Grenadines',false,0),
('WS','WSM','Samoa','Samoa',false,0),
('SM','SMR','Saint-Marin','San Marino',false,0),
('ST','STP','Sao Tomé-et-Príncipe','São Tomé and Príncipe',false,0),
('SA','SAU','Arabie saoudite','Saudi Arabia',false,0),
('SN','SEN','Sénégal','Senegal',false,0),
('RS','SRB','Serbie','Serbia',false,0),
('SC','SYC','Seychelles','Seychelles',false,0),
('SL','SLE','Sierra Leone','Sierra Leone',false,0),
('SG','SGP','Singapour','Singapore',false,0),
('SX','SXM','Saint-Martin (partie néerlandaise)','Sint Maarten',false,0),
('SK','SVK','Slovaquie','Slovakia',false,0),
('SI','SVN','Slovénie','Slovenia',false,0),
('SB','SLB','Îles Salomon','Solomon Islands',false,0),
('SO','SOM','Somalie','Somalia',false,0),
('ZA','ZAF','Afrique du Sud','South Africa',false,0),
('SS','SSD','Soudan du Sud','South Sudan',false,0),
('ES','ESP','Espagne','Spain',false,0),
('LK','LKA','Sri Lanka','Sri Lanka',false,0),
('SD','SDN','Soudan','Sudan',false,0),
('SR','SUR','Suriname','Suriname',false,0),
('SE','SWE','Suède','Sweden',false,0),
('CH','CHE','Suisse','Switzerland',false,0),
('SY','SYR','Syrie','Syria',false,0),
('TW','TWN','Taïwan','Taiwan',false,0),
('TJ','TJK','Tadjikistan','Tajikistan',false,0),
('TZ','TZA','Tanzanie','Tanzania',false,0),
('TH','THA','Thaïlande','Thailand',false,0),
('TL','TLS','Timor oriental','Timor-Leste',false,0),
('TG','TGO','Togo','Togo',false,0),
('TK','TKL','Tokelau','Tokelau',false,0),
('TO','TON','Tonga','Tonga',false,0),
('TT','TTO','Trinité-et-Tobago','Trinidad and Tobago',false,0),
('TN','TUN','Tunisie','Tunisia',false,0),
('TR','TUR','Turquie','Turkey',false,0),
('TM','TKM','Turkménistan','Turkmenistan',false,0),
('TC','TCA','Îles Turques-et-Caïques','Turks and Caicos Islands',false,0),
('TV','TUV','Tuvalu','Tuvalu',false,0),
('UG','UGA','Ouganda','Uganda',false,0),
('UA','UKR','Ukraine','Ukraine',false,0),
('AE','ARE','Émirats arabes unis','United Arab Emirates',false,0),
('GB','GBR','Royaume-Uni','United Kingdom',false,0),
('US','USA','États-Unis','United States',false,0),
('UY','URY','Uruguay','Uruguay',false,0),
('UZ','UZB','Ouzbékistan','Uzbekistan',false,0),
('VU','VUT','Vanuatu','Vanuatu',false,0),
('VA','VAT','Vatican','Vatican City',false,0),
('VE','VEN','Venezuela','Venezuela',false,0),
('VN','VNM','Viêt Nam','Vietnam',false,0),
('VG','VGB','Îles Vierges britanniques','British Virgin Islands',false,0),
('VI','VIR','Îles Vierges américaines','US Virgin Islands',false,0),
('WF','WLF','Wallis-et-Futuna','Wallis and Futuna',false,0),
('EH','ESH','Sahara occidental','Western Sahara',false,0),
('YE','YEM','Yémen','Yemen',false,0),
('ZM','ZMB','Zambie','Zambia',false,0),
('ZW','ZWE','Zimbabwe','Zimbabwe',false,0)
ON CONFLICT (code) DO NOTHING;
