-- 039_countries_regions.sql
-- Ajoute region et subregion (classification UN M49) à la table countries.
-- Permet le tri et filtrage par zone géographique dans le backoffice et le checkout.

ALTER TABLE countries ADD COLUMN IF NOT EXISTS region    text;
ALTER TABLE countries ADD COLUMN IF NOT EXISTS subregion text;

CREATE INDEX IF NOT EXISTS idx_countries_region ON countries(region);

-- Mise à jour des 249 pays avec leurs régions UN M49
-- Régions : Africa, Americas, Asia, Europe, Oceania, Antarctica
-- Sous-régions : Northern Africa, Western Africa, Eastern Africa, Middle Africa, Southern Africa,
--   Northern America, Central America, South America, Caribbean,
--   Central Asia, Eastern Asia, Southern Asia, South-Eastern Asia, Western Asia,
--   Northern Europe, Western Europe, Eastern Europe, Southern Europe,
--   Australia and New Zealand, Melanesia, Micronesia, Polynesia

UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='AF';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='AL';
UPDATE countries SET region='Africa', subregion='Northern Africa' WHERE code='DZ';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='AS';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='AD';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='AO';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='AI';
UPDATE countries SET region='Antarctica', subregion='Antarctica' WHERE code='AQ';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='AG';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='AR';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='AM';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='AW';
UPDATE countries SET region='Oceania', subregion='Australia and New Zealand' WHERE code='AU';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='AT';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='AZ';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='BS';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='BH';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='BD';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='BB';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='BY';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='BE';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='BZ';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='BJ';
UPDATE countries SET region='Americas', subregion='Northern America' WHERE code='BM';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='BT';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='BO';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='BQ';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='BA';
UPDATE countries SET region='Africa', subregion='Southern Africa' WHERE code='BW';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='BR';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='BN';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='BG';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='BF';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='BI';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='CV';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='KH';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='CM';
UPDATE countries SET region='Americas', subregion='Northern America' WHERE code='CA';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='KY';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='CF';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='TD';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='CL';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='CN';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='CO';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='KM';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='CG';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='CD';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='CK';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='CR';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='CI';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='HR';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='CU';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='CW';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='CY';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='CZ';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='DK';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='DJ';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='DM';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='DO';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='EC';
UPDATE countries SET region='Africa', subregion='Northern Africa' WHERE code='EG';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='SV';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='GQ';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='ER';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='EE';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='SZ';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='ET';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='FK';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='FO';
UPDATE countries SET region='Oceania', subregion='Melanesia' WHERE code='FJ';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='FI';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='FR';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='GF';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='PF';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='GA';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='GM';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='GE';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='DE';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='GH';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='GI';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='GR';
UPDATE countries SET region='Americas', subregion='Northern America' WHERE code='GL';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='GD';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='GP';
UPDATE countries SET region='Oceania', subregion='Micronesia' WHERE code='GU';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='GT';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='GG';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='GN';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='GW';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='GY';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='HT';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='HN';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='HK';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='HU';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='IS';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='IN';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='ID';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='IR';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='IQ';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='IE';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='IM';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='IL';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='IT';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='JM';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='JP';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='JE';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='JO';
UPDATE countries SET region='Asia', subregion='Central Asia' WHERE code='KZ';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='KE';
UPDATE countries SET region='Oceania', subregion='Micronesia' WHERE code='KI';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='KP';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='KR';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='KW';
UPDATE countries SET region='Asia', subregion='Central Asia' WHERE code='KG';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='LA';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='LV';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='LB';
UPDATE countries SET region='Africa', subregion='Southern Africa' WHERE code='LS';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='LR';
UPDATE countries SET region='Africa', subregion='Northern Africa' WHERE code='LY';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='LI';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='LT';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='LU';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='MO';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='MG';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='MW';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='MY';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='MV';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='ML';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='MT';
UPDATE countries SET region='Oceania', subregion='Micronesia' WHERE code='MH';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='MQ';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='MR';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='MU';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='YT';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='MX';
UPDATE countries SET region='Oceania', subregion='Micronesia' WHERE code='FM';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='MD';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='MC';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='MN';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='ME';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='MS';
UPDATE countries SET region='Africa', subregion='Northern Africa' WHERE code='MA';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='MZ';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='MM';
UPDATE countries SET region='Africa', subregion='Southern Africa' WHERE code='NA';
UPDATE countries SET region='Oceania', subregion='Micronesia' WHERE code='NR';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='NP';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='NL';
UPDATE countries SET region='Oceania', subregion='Melanesia' WHERE code='NC';
UPDATE countries SET region='Oceania', subregion='Australia and New Zealand' WHERE code='NZ';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='NI';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='NE';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='NG';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='NU';
UPDATE countries SET region='Oceania', subregion='Australia and New Zealand' WHERE code='NF';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='MK';
UPDATE countries SET region='Oceania', subregion='Micronesia' WHERE code='MP';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='NO';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='OM';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='PK';
UPDATE countries SET region='Oceania', subregion='Micronesia' WHERE code='PW';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='PS';
UPDATE countries SET region='Americas', subregion='Central America' WHERE code='PA';
UPDATE countries SET region='Oceania', subregion='Melanesia' WHERE code='PG';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='PY';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='PE';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='PH';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='PN';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='PL';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='PT';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='PR';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='QA';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='RE';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='RO';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='RU';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='RW';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='BL';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='SH';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='KN';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='LC';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='MF';
UPDATE countries SET region='Americas', subregion='Northern America' WHERE code='PM';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='VC';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='WS';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='SM';
UPDATE countries SET region='Africa', subregion='Middle Africa' WHERE code='ST';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='SA';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='SN';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='RS';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='SC';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='SL';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='SG';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='SX';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='SK';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='SI';
UPDATE countries SET region='Oceania', subregion='Melanesia' WHERE code='SB';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='SO';
UPDATE countries SET region='Africa', subregion='Southern Africa' WHERE code='ZA';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='GS';
UPDATE countries SET region='Asia', subregion='Southern Asia' WHERE code='LK';
UPDATE countries SET region='Africa', subregion='Northern Africa' WHERE code='SD';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='SR';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='SJ';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='SE';
UPDATE countries SET region='Europe', subregion='Western Europe' WHERE code='CH';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='SY';
UPDATE countries SET region='Asia', subregion='Eastern Asia' WHERE code='TW';
UPDATE countries SET region='Asia', subregion='Central Asia' WHERE code='TJ';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='TZ';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='TH';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='TL';
UPDATE countries SET region='Africa', subregion='Western Africa' WHERE code='TG';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='TK';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='TO';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='TT';
UPDATE countries SET region='Africa', subregion='Northern Africa' WHERE code='TN';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='TR';
UPDATE countries SET region='Asia', subregion='Central Asia' WHERE code='TM';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='TC';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='TV';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='UG';
UPDATE countries SET region='Europe', subregion='Eastern Europe' WHERE code='UA';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='AE';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='GB';
UPDATE countries SET region='Americas', subregion='Northern America' WHERE code='US';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='UY';
UPDATE countries SET region='Asia', subregion='Central Asia' WHERE code='UZ';
UPDATE countries SET region='Oceania', subregion='Melanesia' WHERE code='VU';
UPDATE countries SET region='Europe', subregion='Southern Europe' WHERE code='VA';
UPDATE countries SET region='Americas', subregion='South America' WHERE code='VE';
UPDATE countries SET region='Asia', subregion='South-Eastern Asia' WHERE code='VN';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='VG';
UPDATE countries SET region='Americas', subregion='Caribbean' WHERE code='VI';
UPDATE countries SET region='Oceania', subregion='Polynesia' WHERE code='WF';
UPDATE countries SET region='Africa', subregion='Northern Africa' WHERE code='EH';
UPDATE countries SET region='Asia', subregion='Western Asia' WHERE code='YE';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='ZM';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='ZW';
UPDATE countries SET region='Europe', subregion='Northern Europe' WHERE code='AX';
UPDATE countries SET region='Africa', subregion='Eastern Africa' WHERE code='SS';
