# mosquitto.dev.conf — config locale (pas de DB, auth par fichier password)
# Utilisé par docker-compose.dev.yml

listener 1883 0.0.0.0
protocol mqtt

allow_anonymous false
password_file /mosquitto/config/passwd

persistence false

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
