; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_qtpy_esp32c3]
platform = espressif32@6.5.0
board = adafruit_qtpy_esp32c3
framework = arduino

; Vitesse moniteur
monitor_speed = 115200
monitor_filters = time

; Partitions larges (si tu en as besoin)
board_build.partitions = huge_app.csv

; Upload rapide + USB CDC
upload_speed = 921600

; Dépendances minimales (WiFi/Web/Prefs). Ajoute PubSubClient si tu en as besoin plus tard.
lib_deps =
  WiFi@2.0.0
  WebServer@2.0.0
  Preferences@2.0.0

build_type = release
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=3
  -Os
  -ffunction-sections
  -fdata-sections
  -Wl,--gc-sections
